services:
    nr_hide_unavailable_variants.decorator.matrix_grid_order_manager_decorator:
        class: 'Netresearch\HideUnavailableVariantsBundle\Decorator\MatrixGridOrderManagerDecorator'
        decorates: oro_shopping_list.provider.matrix_grid_order_manager
        arguments:
            - '@property_accessor'
            - '@oro_product.provider.product_variant_availability_provider'
            - '@oro_shopping_list.manager.empty_matrix_grid'
            - '@doctrine'
            - "@.inner"

    nr_hide_unavailable_variants.decorator.enum_type_handler_decorator:
        class: 'Netresearch\HideUnavailableVariantsBundle\Decorator\EnumTypeHandlerDecorator'
        decorates: oro_product.product_variant.type_handler.enum_type_handler
        arguments:
            - '@form.factory'
            - 'Oro\Bundle\ProductBundle\Entity\Product'
            - '@oro_entity_config.config_manager'
            - "@.inner"
